# -*- coding: utf-8 -*-
"""Modelo Predictivo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPOIu1E76vecYUadgBHzG8ERXbOFQGYp
"""

from prophet import Prophet
import pandas as pd
import numpy as np
from matplotlib import pyplot
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, r2_score
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.stattools import adfuller
import statsmodels.api as sm
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.seasonal import seasonal_decompose

# Lectura de los datos
df = pd.read_excel("PredKi.xlsx", parse_dates=['Fecha'], header= 0)

df["Fecha"] = pd.to_datetime(df["Fecha"])
df.set_index("Fecha", inplace=True)

plt.figure(figsize=(12, 6))
plt.plot(df.index, df["CANTIDAD"], label="KILOS", marker="o")
plt.title("Serie de tiempo")
plt.xlabel("Fecha")
plt.ylabel("Cantidad (Kg)")
plt.show()

def adf_test(df, column_name):
    result = sm.tsa.adfuller(df.dropna())
    adf_statistic, p_value = result[0], result[1]

    print(f"\nPrueba de Dickey-Fuller para {column_name}:")
    print(f"Estadístico ADF: {adf_statistic}")
    print(f"Valor p: {p_value}")

    if p_value <= 0.05:
        print(f"La serie de tiempo '{column_name}' es ESTACIONARIA (p <= 0.05)")
    else:
        print(f"La serie de tiempo '{column_name}' NO es estacionaria (p > 0.05)")


adf_test(df["CANTIDAD"], "Cantidad")

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# Cargar los datos
df = pd.read_excel("PredKi.xlsx", parse_dates=['Fecha'])
df = df[['Fecha', 'CANTIDAD']].dropna()
df.set_index('Fecha', inplace=True)

# Preparar los datos para regresión (convertir fechas en valores numéricos)
df['time_index'] = np.arange(len(df))
X = df[['time_index']]
y = df['CANTIDAD']

# Ajustar modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X, y)

# Obtener pendiente
pendiente = modelo.coef_[0]

# Agregar la línea de tendencia al gráfico
df['tendencia'] = modelo.predict(X)

# Mostrar el gráfico
plt.figure(figsize=(12, 5))
plt.plot(df.index, df['CANTIDAD'], label='Serie Original')
plt.plot(df.index, df['tendencia'], color='red', linestyle='--', label='Tendencia (Regresión)')
plt.title('Serie de tiempo ')
plt.xlabel('Fecha')
plt.ylabel('CANTIDAD (Kg)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Ver resultado
if abs(pendiente) < 1e-3:
    print("No se detecta una tendencia significativa.")
elif pendiente > 0:
    print(f"Tendencia creciente detectada (pendiente = {pendiente:.4f}).")
else:
    print(f"Tendencia decreciente detectada (pendiente = {pendiente:.4f}).")

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from prophet import Prophet

# Cargar los datos
df = pd.read_excel("PredKi.xlsx", parse_dates=['Fecha'], header=0)
df["Fecha"] = pd.to_datetime(df["Fecha"])
df.set_index("Fecha", inplace=True)

# Preparar los datos para Prophet
df_prophet = df.reset_index().rename(columns={"Fecha": "ds", "CANTIDAD": "y"})

# Crear y ajustar el modelo Prophet
modelo = Prophet()
modelo.fit(df_prophet)

# Crear fechas futuras para el pronóstico (24 meses = 2 años, puedes ajustar)
future = modelo.make_future_dataframe(periods=12, freq='M')
forecast = modelo.predict(future)

# Graficar los resultados
plt.figure(figsize=(20, 6))

# Serie original
plt.plot(df_prophet['ds'], df_prophet['y'], label='CANTIDAD - Original', marker='o')

# Pronóstico
plt.plot(forecast['ds'], forecast['yhat'], label='CANTIDAD Prophet', linestyle='--', color='red')

# Ajustar formato del eje X para mostrar un mes por etiqueta
ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))  # Una etiqueta cada mes
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))  # Formato Año-Mes

plt.title('Pronóstico de CANTIDAD con Prophet')
plt.xlabel('Fecha')
plt.ylabel('CANTIDAD (Kg)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

future = modelo.make_future_dataframe(periods=24, freq='M')
future = modelo.make_future_dataframe(periods=730, freq='D')  # 2 años diarios

# Predecir con fechas diarias
forecast = modelo.predict(future)

# Crear columna de mes
forecast['mes'] = forecast['ds'].dt.to_period('M')

# Filtrar solo las fechas futuras
ultima_fecha_real = df_prophet['ds'].max()
forecast_futuro = forecast[forecast['ds'] > ultima_fecha_real]

# Agrupar y sumar los valores por mes
sumatoria_mensual = forecast_futuro.groupby('mes')['yhat'].sum().round(2)

# Mostrar resultados
print("Sumatoria mensual del pronóstico (diario):")
print(sumatoria_mensual)

# Convertir la serie a DataFrame
df_sumatoria = sumatoria_mensual.reset_index()
df_sumatoria.columns = ['Mes', 'Cantidad_Pronosticada']

# Exportar a Excel
df_sumatoria.to_excel("Pronostico_mensual.xlsx", index=False)

print("Archivo Excel guardado como 'Pronostico_mensual.xlsx'")

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from prophet import Prophet

# Cargar los datos
df = pd.read_excel("PredKi2.xlsx", parse_dates=['Fecha'], header=0)
df["Fecha"] = pd.to_datetime(df["Fecha"])
df.set_index("Fecha", inplace=True)

# Preparar los datos para Prophet
df_prophet = df.reset_index().rename(columns={"Fecha": "ds", "CANTIDAD": "y"})

# Crear y ajustar el modelo Prophet
modelo = Prophet()
modelo.fit(df_prophet)

# Crear fechas futuras para el pronóstico (24 meses = 2 años, puedes ajustar)
future = modelo.make_future_dataframe(periods=12, freq='M')
forecast = modelo.predict(future)

# Graficar los resultados
plt.figure(figsize=(20, 6))

# Serie original
plt.plot(df_prophet['ds'], df_prophet['y'], label='CANTIDAD - Original', marker='o')

# Pronóstico
plt.plot(forecast['ds'], forecast['yhat'], label='CANTIDAD Prophet', linestyle='--', color='red')

# Ajustar formato del eje X para mostrar un mes por etiqueta
ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))  # Una etiqueta cada mes
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))  # Formato Año-Mes

plt.title('Pronóstico de CANTIDAD con Prophet')
plt.xlabel('Fecha')
plt.ylabel('CANTIDAD (Kg)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()